import numpy as np
import scipy as sp
import matplotlib.pyplot as plt


class ArrivalTime():
    """ Compute arrival time proposals for a superposition of Gaussian wave packets, with detector located at x = 0."""
    def __init__(self, train):
        """ Initialize superposition of Gaussian packets.
        Parameters:
        packets : class
            Superposition generated by GaussianTrain().
        """
        self.condwavefunc = train.condsuperposition
        self.wavefunc = train.superposition # Superposition
        self.toa = {} # Arrival time distributions

    def quantumclock(self, tVar, tLim, xdtc):
        """ Compute quantum clock (Page-Wootters) proposal.
        Parameters:
        tVar : float or array-like
            Time variable.
        tLim : tuple or array-like
            Temporal domain.
        """
        dt = tVar[1]-tVar[0]
        def toa(t):
            """ Arrival time distribution. 
            Parameters:
            t : float or array-like
                Time variable.
            """ 

            return np.abs(self.wavefunc(t, xdtc))**2
        
        wave = toa(tVar)

        norm, _ = sp.integrate.quad(toa, tLim[0], tLim[1])
    
        self.toa['Quantum clock'] = wave/norm 


    def quantumclockdet(self, tVar, tLim, xDtc):
        """ Compute quantum clock (Page-Wootters) proposal.
        Parameters:
        tVar : float or array-like
            Time variable.
        tLim : tuple or array-like
            Temporal domain.
        xDtc : float
            Detector position for density (xDtc[0] = beginning of detector, xDtc[1] = ending of detector, for arrival time distributions)
        """
        def toaf(t, xDtc):
            """ Arrival time distribution. 
            Parameters:
            t : float or array-like
                Time variable.
            """
            func, _ = sp.integrate.quad(lambda x: np.abs(self.wavefunc(t, x))**2, xDtc[0], xDtc[1])
            return func

        norm, _ = sp.integrate.dblquad(lambda x, t: np.abs(self.wavefunc(t, x))**2, tLim[0], tLim[1], xDtc[0], xDtc[1])
        
        self.toa['Quantum Clock Finite-Size Detector'] = []
        for i in range(0, len(tVar)):
            self.toa['Quantum Clock Finite-Size Detector'] += [toaf(tVar[i], xDtc)/norm]

    def click_DetRes(self, tVar, xVar, xDtc, numPoints, numclick): #Distribution for δt = δL/p
        """ Compute click proposal.
        Parameters:
        tVar : float or array-like
            Time variable.
        tLim : tuple or array-like
            Temporal domain.
        xDtc : array

        """ 
        dt = tVar[1] - tVar[0]
        click = numclick * dt
        dx = xVar[1] - xVar[0]

        
        def toa(t):
            """ Arrival time distribution. 
            Parameters:
            t : float or array-like
                Time variable.
            """ 
            return (self.condwavefunc(t, xVar, xDtc, click, numclick)) 
        
        wave = toa(tVar[0])
        norm = np.sum(wave)*click
        self.toa['Click Approach δt = δL/p0'] = wave/norm

    def clickapproach(self, tVar, xVar, xDtc, numPoints, numclick): 
        """ Compute click proposal.
        Parameters:
        tVar : float or array-like
            Time variable.
        tLim : tuple or array-like
            Temporal domain.
        xDtc : array

        """ 
        dt = tVar[1] - tVar[0]
        click = numclick * dt
        dx = xVar[1] - xVar[0]

        
        def toa(t):
            """ Arrival time distribution. 
            Parameters:
            t : float or array-like
                Time variable.
            """ 
            return (self.condwavefunc(t, xVar, xDtc, click, numclick)) 
        
        wave = toa(tVar[0])
        norm = np.sum(wave)*click

        self.toa['Click Approach'] = wave/norm 


    def quantumflux(self, tVar, tLim):
        """ Compute quantum flux proposal.
        Parameters:
        tVar : float or array-like
            Time variable.
        tLim : tuple or array-like
            Temporal domain.
        """
        deriv = np.zeros_like(tVar, dtype = complex)
        def toa(tVar):
            """ Arrival time distribution. 
            Parameters:
            tVar : float or array-like
                Time variable.
            """
            scalar = np.isscalar(tVar) # Check scalar
            tArr = np.atleast_1d(tVar) # Ensure array
            for idx, t in enumerate(tArr):
                real = lambda x: np.real(self.wavefunc(t, x))
                dreal = sp.differentiate.derivative(real, 0.0).df
                imag = lambda x: np.imag(self.wavefunc(t, x))
                dimag = sp.differentiate.derivative(imag, 0.0).df
                deriv[idx] = dreal + 1j*dimag
            result =  np.imag(np.conj(self.wavefunc(tVar, 0))*deriv)
            if scalar: # Quad compatibility
                return float(result[0])
            return result

        norm, _ = sp.integrate.quad(toa, tLim[0], tLim[1])
        self.toa['Quantum flux'] = toa(tVar)/norm

    def visualize(self, numPoints, tLim, xLim, xDtc):
        """ Visualize wave function and compare arrival time proposals.
        Parameters:
        numPoints : int
            Number of points in each dimension (x and t).
        tLim : tuple or array-like
            Temporal domain.
        xLim : tuple or array-like
            Spatial domain.
        xDtc : float
            Detector position for density (xDtc = 0 for arrival time distributions)
        """
        t = np.linspace(tLim[0], tLim[1], numPoints)
        x = np.linspace(xLim[0], xLim[1], numPoints)
        T, X = np.meshgrid(t, x)

        density = np.abs(self.wavefunc(T, X))**2
        densityDtc = np.abs(self.wavefunc(t, xDtc))**2
        self.quantumclock(t,tLim)


        plt.rcParams.update({'font.size': 18})
        plt.rcParams["font.family"] = "serif"
        lines = ['-','--','-','-.']
        markers = ['None', 'None', '^', 'v']
        colors = np.array(['tab:blue', 'tab:orange', 'tab:green', 'tab:red',\
                      'tab:purple','tab:brown'])
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 5), dpi = 400,\
                                            constrained_layout = True) # Figure
        
        pcm = ax1.pcolormesh(T, X, density, shading='auto', cmap='viridis')
        fig.colorbar(pcm, ax = ax1, label="Density")
        ax1.set_xlabel("Time")
        ax1.set_ylabel("Position")
        ax1.title.set_text("Wave packets density")
        ax2.plot(t, densityDtc, color = 'tab:blue', marker = 'None', linestyle = '-',\
                 markersize = 1, linewidth = 1)
        ax2.set_xlabel("Time")
        ax2.title.set_text(f"Density at x = {xDtc}")
        for idx, key in enumerate(self.toa):
            ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = key)
        ax3.set_xlabel("Time")
        ax3.set_ylabel("Probability")
        ax3.title.set_text("Arrival time distributions")
        ax3.legend(loc = 'upper right')
        
        plt.show()


    def visualizec(self, numPoints, tLim, xLim, xDtc, nclick, momento): #tLimWindow, 
        """ Visualize wave function and compare arrival time proposals.
        Parameters:
        numPoints : int
            Number of points in each dimension (x and t).
        tLim : tuple or array-like
            Temporal domain.
        xLim : tuple or array-like
            Spatial domain.
        xDtc : float
            Detector position for density (xDtc = 0 for arrival time distributions)
        """

        t = np.linspace(tLim[0], tLim[1], numPoints)

        x = np.linspace(xLim[0], xLim[1], numPoints)
        T, X = np.meshgrid(t, x)
        density = np.abs(self.wavefunc(T, X))**2

        densityDtc = np.abs(self.wavefunc(t, xDtc[0]+(xDtc[1]-xDtc[0])/2))**2
        self.quantumclock(t, tLim, xDtc[0])

        self.quantumclockdet(t, tLim, xDtc)
        self.clickapproach(t, x, xDtc, numPoints, nclick)

        taux = []
        for i in range(numPoints):
            if i % nclick == 0:
                taux.append(t[i])
        

        plt.rcParams.update({'font.size': 18})
        plt.rcParams["font.family"] = "serif"
        lines = ['-.','--',':','--', '--', '--', '--', '--', '--']
        markers = ['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', '^', 'v']
        colors = np.array(['tab:blue', 'tab:orange', 'tab:green', 'tab:red',\
                      'tab:purple','tab:brown', 'tab:pink', 'tab:grey', 'tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown'])
        fig, (ax3) = plt.subplots(1, 1, figsize=(25, 10), dpi = 400,\
                                            constrained_layout = True)
        
        for idx, key in enumerate(self.toa):
            if key == 'Click Approach': # The time axis is different
                ax3.plot(taux, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = 'Conditioned Dist.')
            else:
                if key == 'Quantum clock':
                    ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = 'Point-Like Non-Conditioned Dist.')
                else:
                    ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = 'Finite-Size Non-Conditioned Dist.')
        ax3.set_xlabel("Time")
        ax3.set_ylabel("Probability")
        ax3.title.set_text("Arrival time distributions")
        ax3.legend(loc = 'upper center', bbox_to_anchor=(0.5, -0.05), shadow=True, ncol=5)
        plt.show()


    def visualizemult(self, numPoints, tLim, xLim, xDtc, nclick, momento): # Multiple distribution with different time resolutions
        """ Visualize wave function and compare arrival time proposals.
        Parameters:
        numPoints : int
            Number of points in each dimension (x and t).
        tLim : tuple or array-like
            Temporal domain.
        xLim : tuple or array-like
            Spatial domain.
        xDtc : float
            Detector position for density (xDtc = 0 for arrival time distributions)
        """

        t = np.linspace(tLim[0], tLim[1], numPoints)

        x = np.linspace(xLim[0], xLim[1], numPoints)
        T, X = np.meshgrid(t, x)
        density = np.abs(self.wavefunc(T, X))**2

        densityDtc = np.abs(self.wavefunc(t, xDtc[0]+(xDtc[1]-xDtc[0])/2))**2
        self.quantumclock(t, tLim, xDtc[0])#+(xDtc[1]-xDtc[0])/2

        self.quantumclockdet(t, tLim, xDtc)
        self.clickapproach(t, x, xDtc, numPoints, nclick)

        detclick = (xDtc[1]-xDtc[0]) / (2*momento) # δt = δL/p0 
        numclick = int(detclick/(t[1] - t[0])) # This gives the number of ideal clicks contained in this resolution
        self.click_DetRes(t, x, xDtc, numPoints, numclick)

        
        taux = []
        taux1 = []
        for i in range(numPoints):
            if i % nclick == 0:
                taux.append(t[i])
            if i % numclick == 0:
                taux1.append(t[i])
        

        plt.rcParams.update({'font.size': 18})
        plt.rcParams["font.family"] = "serif"
        lines = ['-','--',':','--', '--', '--', '--', '--', '--']
        markers = ['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', '^', 'v']
        colors = np.array(['tab:blue', 'tab:orange', 'tab:green', 'tab:red',\
                      'tab:purple','tab:brown', 'tab:pink', 'tab:grey', 'tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown'])
        fig, (ax3) = plt.subplots(1, 1, figsize=(25, 10), dpi = 400,\
                                            constrained_layout = True)
        
        for idx, key in enumerate(self.toa):
            if key == 'Click Approach': # The time axis is different
                ax3.plot(taux, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = 'Conditioned Dist.')

                self.clickapproach(t, x, xDtc, numPoints, 70*nclick)
                taux = []
                for i in range(numPoints):
                    if i % (70*nclick) == 0:
                        taux.append(t[i])
                ax3.plot(taux, self.toa[key], color = colors[idx+4], marker = markers[idx+4], linestyle = lines[idx+4],\
                     markersize = 1, linewidth = 1, label = 'Conditioned Dist. 70δt')
            
            else:
                if key == 'Click Approach δt = δL/p0': # The time axis is different
                    ax3.plot(taux1, self.toa[key], color = colors[idx+1], marker = markers[idx], linestyle = lines[idx],\
                     markersize = 1, linewidth = 1, label = 'Conditioned Dist. δt = δL/p0')
                else:
                    if key == 'Quantum clock':
                        ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = '-',\
                     markersize = 1, linewidth = 1, label = 'Point-Like Non-Conditioned Dist.')
                    else:
                        ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = '-',\
                     markersize = 1, linewidth = 1, label = 'Finite-Size Non-Conditioned Dist.')
        ax3.set_xlabel("Time")
        ax3.set_ylabel("Probability")
        ax3.title.set_text("Arrival time distributions")
        ax3.legend(loc = 'upper center', bbox_to_anchor=(0.5, -0.05), shadow=True, ncol=5)
        plt.show()

        
    def compare(self, tLim):
        self.toa['Click Approach 1'] = np.load('./Click_Exp1.npy')
        self.toa['Click Approach 2'] = np.load('./Click_Exp2.npy')
        self.toa['Click Approach 3'] = np.load('./Click_Exp3.npy')


        plt.rcParams.update({'font.size': 18})
        plt.rcParams["font.family"] = "serif"
        lines = ['-','--',':','--', '--', '--', '--', '--', '--']
        markers = ['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', '^', 'v']
        colors = np.array(['tab:blue', 'tab:orange', 'tab:green', 'tab:red',\
                      'tab:purple','tab:brown', 'tab:pink', 'tab:grey', 'tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown'])
        fig, (ax3) = plt.subplots(1, 1, figsize=(25, 10), dpi = 400,\
                                            constrained_layout = True)

        for idx, key in enumerate(self.toa):
            if key == 'Click Approach 1' or key == 'Click Approach 2' or key == 'Click Approach 3':
                n = len(self.toa[key])
                t = np.linspace(tLim[0], tLim[1], n)
                ax3.plot(t, self.toa[key], color = colors[idx], marker = markers[idx], linestyle = lines[idx],markersize = 1, linewidth = 1, label = key)
        
        ax3.set_xlabel("Time")
        ax3.set_ylabel("Probability")
        ax3.title.set_text("Arrival time distributions")
        ax3.legend(loc = 'upper center', bbox_to_anchor=(0.5, -0.05), shadow=True, ncol=5)
        plt.show()
